### ISSUE TITLE
Request: Can you add roles to tulpa avatars?

### ISSUE THREAD

**Issue by StarDragon69** [kartelant/Tupperbox#40]
Hello! I've been using tupperbox for roleplaying and the like, and I find it really fun to use! I love the set of features it has already, but if possible are you able to make it so members can assign roles onto these bots? Thanks!

**Comment by kartelant** [comment]
Unfortunately, this isn't possible with Discord's existing systems. Webhooks are unable to have roles or name colors. If you'd like this feature, suggest to Discord the ability to color webhook names!

**Comment by StarDragon69** [comment]
Alright! Thank you!
