### ISSUE TITLE
Automatic resizing of Avatars

### ISSUE THREAD

**Issue by Kazilii** [kartelant/Tupperbox#47]
To avoid Discords size limit on avatars, Tupperbox should allow any size image and automatically scale it down for the user.
Many people either don't know how, or don't have the patience to do this themselves, and this could prove to be a nice quality of life update.

**Comment by kartelant** [comment]
This has been an idea floated for quite some time, the only problem is that while I could resize the image, it'd have to be uploaded somewhere to be permanent, and I don't really want to handle relying on some site to keep the images. If you can think of a workaround I'm all ears, but that's the current state of this suggestion.

**Comment by Kazilii** [comment]
The solution I used is to send them to a private discord channel as an attachment, and then store the link to said attachment for the Webhooks avatar.
